# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Onuralp SEZER <thunderbirdtr@fedoraproject.org>

install(FILES
    icons/plasma-light-and-presence.svg
    icons/plasma-light-and-presence-symbolic.svg
    icons/plasma-light-and-presence-off-symbolic.svg
    DESTINATION ${KDE_INSTALL_ICONDIR}/hicolor/scalable/apps)
