# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Onuralp SEZER <thunderbirdtr@fedoraproject.org>

install(FILES
    icons/io.github.onuralpszr.lightandpresence.svg
    icons/io.github.onuralpszr.lightandpresence-symbolic.svg
    icons/io.github.onuralpszr.lightandpresence-off-symbolic.svg
    DESTINATION ${KDE_INSTALL_ICONDIR}/hicolor/scalable/apps)
