# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Onuralp SEZER <thunderbirdtr@fedoraproject.org>

install(FILES
    icons/plasma-sensord.svg
    icons/plasma-sensord-symbolic.svg
    icons/plasma-sensord-off-symbolic.svg
    DESTINATION ${KDE_INSTALL_ICONDIR}/hicolor/scalable/apps)
